#!/bin/sh
set -e

# This script is executed by the Nginx entrypoint before starting the daemon.
# It checks for the presence of SSL certificates and enables HTTPS if found,
# and templates the API upstream + scheme into common.fragment so the same
# image can front either the backend directly or the strata-dmz relay.

CERT_PATH="/etc/nginx/ssl/cert.pem"
KEY_PATH="/etc/nginx/ssl/key.pem"
TARGET_CONF="/etc/nginx/conf.d/default.conf"
# common.fragment is templated into /etc/nginx/conf.d/ (tmpfs) rather
# than /etc/nginx/ because the container runs read_only=true; only
# /etc/nginx/conf.d is writable at runtime.
COMMON_SRC="/etc/nginx/common.fragment"
COMMON_DST="/etc/nginx/conf.d/common.fragment"

# ── 1. HTTP vs HTTPS server block ─────────────────────────────────────
echo "Checking for SSL certificates..."

if [ -f "$CERT_PATH" ] && [ -f "$KEY_PATH" ]; then
    echo "SSL certificates detected. Activating HTTPS configuration."
    cp /etc/nginx/https_enabled.conf "$TARGET_CONF"
else
    echo "SSL certificates missing. Activating HTTP-only fallback."
    cp /etc/nginx/http_only.conf "$TARGET_CONF"
fi

# Ensure common.fragment is always in the right place (if not already copied)
if [ ! -f "$COMMON_SRC" ]; then
    cp /etc/nginx/templates/common.fragment "$COMMON_SRC"
fi

# ── 2. API upstream templating ────────────────────────────────────────
# common.fragment ships with two markers (__STRATA_API_UPSTREAM__,
# __STRATA_API_SCHEME__) that this step replaces with values from the
# environment. Defaults preserve the historical "frontend → backend"
# wiring so non-DMZ deployments are unaffected.
API_UPSTREAM="${STRATA_API_UPSTREAM:-backend:8080}"
API_SCHEME="${STRATA_API_SCHEME:-http}"

if [ "$API_SCHEME" != "http" ] && [ "$API_SCHEME" != "https" ]; then
    echo "ssl-init: invalid STRATA_API_SCHEME='$API_SCHEME' (expected http or https)" >&2
    exit 1
fi

echo "Templating /api/ upstream: $API_SCHEME://$API_UPSTREAM"
sed \
    -e "s|__STRATA_API_UPSTREAM__|${API_UPSTREAM}|g" \
    -e "s|__STRATA_API_SCHEME__|${API_SCHEME}|g" \
    "$COMMON_SRC" > "$COMMON_DST"

# ── 3. proxy_ssl_* directives for HTTPS upstreams ─────────────────────
# When the upstream is the DMZ relay (https), nginx must validate the
# relay's TLS chain. The CA bundle is expected at
# /etc/nginx/ssl/upstream-ca.pem (mounted by the docker-compose.dmz-edge
# overlay). For http upstreams the include resolves to an empty file.
SSL_INCLUDE="/etc/nginx/conf.d/api-proxy-ssl.conf"

if [ "$API_SCHEME" = "https" ]; then
    UPSTREAM_CA="${STRATA_API_UPSTREAM_CA:-/etc/nginx/ssl/upstream-ca.pem}"
    # Strip ":port" if present to derive the SNI / cert-hostname.
    SNI_NAME="${STRATA_API_UPSTREAM_SNI:-${API_UPSTREAM%%:*}}"

    if [ ! -f "$UPSTREAM_CA" ]; then
        echo "ssl-init: STRATA_API_SCHEME=https but $UPSTREAM_CA is missing" >&2
        echo "         mount the DMZ CA bundle at that path or override STRATA_API_UPSTREAM_CA" >&2
        exit 1
    fi

    cat > "$SSL_INCLUDE" <<EOF
# Generated by ssl-init.sh — verifies the upstream's TLS chain against
# the CA mounted at $UPSTREAM_CA.
proxy_ssl_verify on;
proxy_ssl_verify_depth 2;
proxy_ssl_trusted_certificate $UPSTREAM_CA;
proxy_ssl_server_name on;
proxy_ssl_name $SNI_NAME;
proxy_ssl_protocols TLSv1.2 TLSv1.3;
EOF
    echo "Wrote $SSL_INCLUDE (SNI=$SNI_NAME, CA=$UPSTREAM_CA)"
else
    : > "$SSL_INCLUDE"
fi

echo "Nginx configuration prepared successfully."
