/* eslint-disable react-hooks/set-state-in-effect --
   react-hooks v7 compiler-strict suppressions: legitimate prop->state sync, session
   decoration, or render-time time/derivation patterns. See
   eslint.config.js W4-1 commentary. */
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { useParams, useSearchParams } from "react-router-dom";
import Guacamole from "guacamole-common-js";
import { createWinKeyProxy } from "../utils/winKeyProxy";
import { useCoPilotRoom } from "../co-pilot/useCoPilotRoom";
import { useCoPilotAudio } from "../co-pilot/useCoPilotAudio";
import CoPilotOverlay from "../co-pilot/CoPilotOverlay";
/**
 * Shared session viewer. Accessible without authentication
 * via a share token generated by the connection owner.
 * Supports 'view' (read-only) and 'control' (full input) modes.
 * v1.9.6+ — when the share URL carries `mp=1`, opens a sibling
 * co-pilot WebSocket for cursors / chat / input-token arbitration.
 */
export default function SharedViewer() {
  const { shareToken } = useParams<{ shareToken: string }>();
  const [searchParams] = useSearchParams();
  const containerRef = useRef<HTMLDivElement>(null);
  const clientRef = useRef<Guacamole.Client | null>(null);
  const [error, setError] = useState("");
  const [connected, setConnected] = useState(false);
  const [mode, setMode] = useState<"view" | "control">("view");
  const [displayScale, setDisplayScale] = useState(1);

  // ── Multiplayer toggle ─────────────────────────────────────────
  // The share creator marks a link as multiplayer-capable via
  // `mp=1`; the user supplies their preferred display name on the
  // landing page via `name=...` (falling back to "Guest").
  const multiplayer = searchParams.get("mp") === "1";
  const displayName = searchParams.get("name") ?? "Guest";
  const [room, roomActions] = useCoPilotRoom(shareToken, displayName, multiplayer);
  // Optional WebRTC audio mesh. `audioJoined` reflects the viewer's
  // opt-in via the overlay toggle.
  const [audioJoined, setAudioJoined] = useState(false);
  useCoPilotAudio({
    roster: room.roster,
    selfPid: room.pid,
    allowAudio: room.allowAudio,
    joined: audioJoined,
    sendAudio: roomActions.sendAudio,
    setAudioHandler: roomActions.setAudioHandler,
  });

  useEffect(() => {
    const urlMode = searchParams.get("mode");
    if (urlMode === "control") setMode("control");
  }, [searchParams]);

  useEffect(() => {
    // In multiplayer mode, defer opening the tunnel WS until the
    // co-pilot handshake has yielded a pid — the server uses it to
    // route input-token gating.
    if (multiplayer && !room.ready) return;
    if (!shareToken || !containerRef.current) return;

    const wsProto = window.location.protocol === "https:" ? "wss:" : "ws:";
    const container = containerRef.current;
    const dpr = window.devicePixelRatio || 1;

    // NOTE: Do NOT append `?pid=...` to the tunnel URL — Guacamole's
    // WebSocketTunnel hard-codes `tunnelURL + "?" + data` when it opens
    // the socket (guacamole-common-js 1.5.0), which would produce a
    // malformed `...?pid=UUID?width=...&height=...` URL where the
    // server parses `pid` as `UUID?width=1920` and UUID parsing fails.
    // Instead we pass `pid` through the connect-data string so it lands
    // after Guacamole's own `?` separator. See `client.connect(...)` below.
    const wsUrl = `${wsProto}//${window.location.host}/api/shared/tunnel/${shareToken}`;
    const tunnel = new Guacamole.WebSocketTunnel(wsUrl);
    const client = new Guacamole.Client(tunnel);
    clientRef.current = client;
    const display = client.getDisplay();
    const displayEl = display.getElement();
    displayEl.style.background = "#000";
    container.appendChild(displayEl);

    // Render remote cursor via CSS (1.6.0 compatibility — see SessionManager).
    display.oncursor = (canvas: HTMLCanvasElement, hotspotX: number, hotspotY: number) => {
      try {
        const url = canvas.toDataURL("image/png");
        displayEl.style.cursor = `url(${url}) ${hotspotX} ${hotspotY}, default`;
      } catch {
        /* ignore */
      }
    };

    // Suppress the 1.6.0 software cursor canvas layer (it stacks on top
    // of the CSS cursor and produces ghost cursors). See SessionManager
    // for the full explanation.
    try {
      const cursorLayer = display.getCursorLayer?.();
      const cursorEl = cursorLayer?.getElement?.();
      cursorEl?.parentNode?.removeChild(cursorEl);
    } catch {
      /* defensive */
    }
    display.showCursor = () => {
      /* no-op */
    };

    // Mouse (view-only still lets the viewer see cursor position).
    // In multiplayer rooms we additionally forward the local pointer
    // to the co-pilot WS as a `cursor` envelope so peers see it.
    const mouse = new Guacamole.Mouse(displayEl);
    mouse.onEach(["mousedown", "mouseup", "mousemove"], (e: Guacamole.Mouse.Event) => {
      client.sendMouseState(e.state, true);
      if (multiplayer) {
        // The mouse state is already in display-space coordinates;
        // `useCoPilotRoom` throttles to ~30 Hz so a tight mousemove
        // burst won't flood the WS.
        roomActions.sendCursor(e.state.x, e.state.y);
      }
    });

    // Keyboard — attached when the viewer actually drives input.
    // In multiplayer this requires holding the input token.
    const urlMode = searchParams.get("mode");
    if (urlMode === "control") {
      const keyboard = new Guacamole.Keyboard(document);
      const winProxy = createWinKeyProxy((p, k) => client.sendKeyEvent(p, k));
      keyboard.onkeydown = (keysym: number) => {
        // Block keyboard locally when we don't hold the token. The
        // server also gates this, but suppressing client-side avoids
        // the surprise of typed text vanishing into the void.
        if (multiplayer && !roomRef.current?.hasInput) return true;
        return winProxy.onkeydown(keysym);
      };
      keyboard.onkeyup = (keysym: number) => {
        if (multiplayer && !roomRef.current?.hasInput) return;
        winProxy.onkeyup(keysym);
      };
    }

    const applyScale = () => {
      const dw = display.getWidth();
      const dh = display.getHeight();
      if (dw <= 0 || dh <= 0) return;
      const cw = container.clientWidth;
      const ch = container.clientHeight;
      if (cw <= 0 || ch <= 0) return;
      const s = Math.min(cw / dw, ch / dh);
      display.scale(s);
      setDisplayScale(s);
    };
    display.onresize = applyScale;

    tunnel.onerror = (status: Guacamole.Status) => {
      setError(status.message || "Connection failed");
    };
    client.onerror = (status: Guacamole.Status) => {
      setError(status.message || "Connection failed");
    };

    client.onstatechange = (state: number) => {
      if (state === 3) {
        setConnected(true);
        requestAnimationFrame(applyScale);
      }
    };

    const connectParams = new URLSearchParams();
    connectParams.set("width", String(container.clientWidth));
    connectParams.set("height", String(container.clientHeight));
    connectParams.set("dpi", String(Math.round(96 * dpr)));
    // Multiplayer input gating: server reads `pid` from the query
    // string to identify which room participant is sending input
    // frames. Must be set here (not on the tunnel URL) — see comment
    // above the WebSocketTunnel construction.
    if (multiplayer && room.pid) connectParams.set("pid", room.pid);

    client.connect(connectParams.toString());

    const handleResize = () => {
      applyScale();
      client.sendSize(container.clientWidth, container.clientHeight);
    };
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
      try {
        client.disconnect();
      } catch {
        /* ignore */
      }
    };
    // searchParams is read once at connect time; re-running on URL changes would tear down the share session
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shareToken, multiplayer, room.ready, room.pid]);

  // Keep an up-to-date snapshot of the room state accessible to the
  // keyboard handlers without re-subscribing them on every roster tick.
  // Lint suppression: legitimate ref-sync pattern — see eslint.config.js W4-1.
  const roomRef = useRef(room);
  useEffect(() => {
    // eslint-disable-next-line react-hooks/immutability
    roomRef.current = room;
  }, [room]);

  return createPortal(
    <div style={{ position: "fixed", inset: 0, zIndex: 5, background: "#000" }}>
      {/* Banner */}
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          zIndex: 10,
          padding: "6px 16px",
          background: "rgba(0,0,0,0.7)",
          backdropFilter: "blur(8px)",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          fontSize: "0.75rem",
          color: "#ccc",
        }}
      >
        <span>
          <strong>Shared Session</strong> —{" "}
          {connected ? (mode === "control" ? "Control mode" : "Read-only view") : "Connecting…"}
          {multiplayer && (
            <span style={{ marginLeft: 8, opacity: 0.7 }}>
              · Multiplayer ({room.roster.length}/{room.maxParticipants})
              {room.hasInput ? " · You have control" : ""}
            </span>
          )}
        </span>
      </div>

      {multiplayer && room.ready && (
        <CoPilotOverlay
          roster={room.roster}
          cursors={room.cursors}
          chat={room.chat}
          allowChat={room.allowChat}
          hasInput={room.hasInput}
          selfPid={room.pid}
          onClaimInput={roomActions.claimInput}
          onReleaseInput={roomActions.releaseInput}
          onSendChat={roomActions.sendChat}
          audioJoined={audioJoined}
          onToggleAudio={room.allowAudio ? () => setAudioJoined((v) => !v) : undefined}
          displayScale={displayScale}
        />
      )}

      <div
        ref={containerRef}
        style={{
          width: "100%",
          height: "100%",
          overflow: "hidden",
        }}
      />

      {error && (
        <div
          className="absolute inset-0 flex items-center justify-center z-20"
          style={{ background: "rgba(0,0,0,0.85)" }}
        >
          <div style={{ textAlign: "center", color: "#fff", maxWidth: 400, padding: 32 }}>
            <div style={{ fontSize: "2rem", marginBottom: 8 }}>⚠</div>
            <div style={{ color: "#f87171", marginBottom: 16 }}>{error}</div>
            <p style={{ fontSize: "0.8rem", color: "#999" }}>
              This share link may have expired, been revoked by the owner, or the owner may not be
              actively connected.
            </p>
          </div>
        </div>
      )}
    </div>,
    document.getElementById("root")!
  );
}
